---
# Ansible Galaxy requirements file
# External dependencies for ansible-roles

collections:
  - name: community.general
    version: ">=5.0.0"

# roles:
#   - src: https://github.com/some-org/some-role
#     version: main
#     name: some-role
