---
- name: Install ZSH
  ansible.builtin.package:
    name: zsh
    state: present

- name: Set ZSH as default shell for root
  ansible.builtin.user:
    name: root
    shell: /bin/zsh
  when: baseline_zsh_default_shell | bool
