---
# tasks file for baseline

- name: Detect cloud provider
  ansible.builtin.include_tasks: detect-cloud-provider.yml
  when: baseline_detect_cloud_provider | bool

- name: Update system packages
  ansible.builtin.include_tasks: "update-{{ ansible_facts['os_family'] | lower }}.yml"
  when: baseline_update_system | bool

- name: Install base packages
  ansible.builtin.package:
    name: "{{ baseline_packages }}"
    state: present

- name: Install ZSH
  ansible.builtin.include_tasks: install-zsh.yml
  when: baseline_install_zsh | bool

- name: Rotate SSH host keys
  ansible.builtin.include_tasks: rotate-ssh-keys.yml
  when: baseline_rotate_ssh_keys | bool

- name: Install AWS CLI
  ansible.builtin.include_tasks: install-aws-cli.yml
  when:
    - baseline_install_aws_cli | bool
    - cloud_provider is defined
    - cloud_provider == "aws"

- name: Configure root git identity
  ansible.builtin.include_tasks: configure-root-git.yml
  when: baseline_install_etckeeper | bool

- name: Install and configure etckeeper
  ansible.builtin.include_tasks: install-etckeeper.yml
  when: baseline_install_etckeeper | bool
