---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ baseline_update_cache_valid_time }}"

- name: Upgrade all packages (Debian/Ubuntu)
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
