---
# handlers file for baseline

- name: Restart sshd
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: Etckeeper init
  ansible.builtin.command: etckeeper init
  args:
    creates: /etc/.git
